### PR TITLE
Fixed TomTom routing

### PR DESCRIPTION
**Pull request by rijnb**
The TomTom routing was broken. It used the locations of instructions to draw a poyline, rather than the locations of the route itself. It also added parameters to the TomTom URL, which are not needed (and only make the resulting JSON larger).

### CODE REVIEW

**Comment by MSBilgin** [comment]
Thanks for PR but i checked the plugin without error. TomTom API works well. But MapQuest and Graphopper could be changed.

**Comment by rijnb** [comment]
Hi Mehmet,

The current call only retrieves locations for the spoken instructions (what we call decision points). This approximates the route but not accurately. What you want is the full polyline. Hence the PR. This will use the full polyline for the route  instead. I checked with the online  API team and the PR should be fine (I mean the TomTom dev team for online routing).
Or if something is wrong with the PR let me know, perhaps I can help.

Best regards,
Rijn Buve
Director of Technology of TomTom

----
rijn@buve.nl

Op 22 mei 2017 om 10:21 heeft Mehmet Selim BILGIN <notifications@github.com> het volgende geschreven:

Thanks for PR but i checked the plugin without error. TomTom API works well. But MapQuest and Graphopper could be changed.

**Comment by MSBilgin** [comment]
Hi Rijn, i see your PR makes the plugin works better, thank you.

**Comment by rijnb** [comment]
Any time ;-)

Regards,
-Rijn

----
rijn@buve.nl

Op 23 mei 2017 om 09:19 heeft Mehmet Selim BILGIN <notifications@github.com> het volgende geschreven:

Hi Rijn, i see your PR makes the plugin works better, thank you.

**Pull request merged**
